services:
  front:
    container_name: kot_front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3000
    networks:
      - front

networks:
  front:
    name: kot_front_network
    driver: bridge
